adding backups and readme.md
bcgov/DITP-DevOps pull request #77
Opened 2023-05-29 23:35 UTC by rajpalc7

adding dashboard backups and readme file

2023-05-30 18:49 UTC, WadeBarnes requested changes

2023-05-30 18:49 UTC, WadeBarnes commented on sysdig/dashboard backups/readme.md
This document covers how to use the sysdig tool a bit, bit it does not cover where to get it or how to install it.

Under the `Setup Env variables` it talks about needing 2 environment variables but onto lists one.  It also talks about needing an API token, but does not indicate how or were to use it.  There is also a section on a docker image, but where are the associated files?

Was this document taken from another repository?  If so it would likely be easier to writeup a summary guide showing how to use the tools for our purpose that provides a like to the other repository for the details.

2023-06-21 17:36 UTC, WadeBarnes commented on sysdig/dashboard backups/readme.md
@rajpalc7, When you get a change could you please address these issues.  Thanks

2023-06-21 17:39 UTC, rajpalc7 commented on sysdig/dashboard backups/readme.md
Sounds good Wade, What will be the first priority - sprint ticket or this issue ?

2023-06-21 19:04 UTC, WadeBarnes commented on sysdig/dashboard backups/readme.md
Sprint ticket

2023-07-05 22:19 UTC, rajpalc7 commented
Hi @WadeBarnes , documentation has been updated now. Please let me know if it requires any additional changes.

2023-07-11 15:44 UTC, WadeBarnes requested changes

2023-07-11 15:44 UTC, WadeBarnes commented on Terraform/silver-e79518-team/.terraform/providers/registry.terraform.io/sysdiglabs/sysdig/0.5.37/windows_amd64/README.md
@rajpalc7, did you mean to add this document?  It was added with the commit message "deleting README.md".  If you did mean to add it, what is it's relevance to the other files you've added to the PR?

2023-07-11 15:48 UTC, rajpalc7 commented on Terraform/silver-e79518-team/.terraform/providers/registry.terraform.io/sysdiglabs/sysdig/0.5.37/windows_amd64/README.md
Hi @WadeBarnes , there is no relevance of this file and it came with the terraform package and we didnt needed it so I decided to delete it.

2023-07-11 15:52 UTC, WadeBarnes commented on Terraform/silver-e79518-team/.terraform/providers/registry.terraform.io/sysdiglabs/sysdig/0.5.37/windows_amd64/README.md
Well, you inadvertently added it rather than deleting it.

2023-07-11 16:08 UTC, rajpalc7 commented on Terraform/silver-e79518-team/.terraform/providers/registry.terraform.io/sysdiglabs/sysdig/0.5.37/windows_amd64/README.md
No worries wade, i will remove that commit from the branch to fix it

2023-07-11 19:09 UTC, rajpalc7 commented
https://github.com/bcgov/DITP-DevOps/pull/84/commits - Hey Wade, I have just created a new branch and added the changed there

2023-07-12 12:45 UTC, WadeBarnes commented
Closing in favor of https://github.com/bcgov/DITP-DevOps/pull/77

2023-07-12 12:45 UTC, closed without merging